version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snaildb
      MYSQL_USER: snailuser
      MYSQL_PASSWORD: snailpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  snail-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snail-app-1
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_URL: ${MONGO_DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_KEY_EXPIRATION_SECONDS: ${ACCESS_KEY_EXPIRATION_SECONDS}
      REFRESH_KEY_EXPIRATION_SECONDS: ${REFRESH_KEY_EXPIRATION_SECONDS}
      DB_URL: jdbc:mysql://mysql:3306/snaildb
      DB_USER_NAME: snailuser
      DB_PASSWORD: snailpass
    ports:
      - "8082:8080"
    depends_on:
      - mysql

  snail-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snail-app-2
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_URL: ${MONGO_DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_KEY_EXPIRATION_SECONDS: ${ACCESS_KEY_EXPIRATION_SECONDS}
      REFRESH_KEY_EXPIRATION_SECONDS: ${REFRESH_KEY_EXPIRATION_SECONDS}
      DB_URL: jdbc:mysql://mysql:3306/snaildb
      DB_USER_NAME: snailuser
      DB_PASSWORD: snailpass
    ports:
      - "8083:8080"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - snail-app-1
      - snail-app-2


volumes:
  mysql-data:
