version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snaildb
      MYSQL_USER: snailuser
      MYSQL_PASSWORD: snailpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  snail-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snail-app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_URL: ${MONGO_DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_KEY_EXPIRATION_SECONDS: ${ACCESS_KEY_EXPIRATION_SECONDS}
      REFRESH_KEY_EXPIRATION_SECONDS: ${REFRESH_KEY_EXPIRATION_SECONDS}
      DB_URL: jdbc:mysql://mysql:3306/snaildb
      DB_USER_NAME: snailuser
      DB_PASSWORD: snailpass
    depends_on:
        - mysql

volumes:
  mysql-data: