services:
  snail-app-1:
    image: minseok1768/snail-app:latest
    container_name: snail-app-1
    env_file:
      - .env
    ports:
      - "8082:8080"
    restart: always

  snail-app-2:
    image: minseok1768/snail-app:latest
    container_name: snail-app-2
    env_file:
      - .env
    ports:
      - "8083:8080"
    restart: always


  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - snail-app-1
      - snail-app-2
    restart: always
