receivers: # Collector 가 데이터를 받는 방식 (어디서 데이터를 받을지)
  otlp: # java 애플리케이션에서 OTLP(OpenTelemetry Protocol) 로 메트릭/트레이스를 Collector 로 전송
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"  # 이 줄이 필요!


exporters: #(어디로 데이터를 보낼지)
  prometheus: # Collector 가 수집한 메트릭을 Prometheus 가 긁어 갈 수 있도록 /metrics 엔드포인트(8889)에 노출
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: ticketon-service

  otlp/tempo: # 트레이스를 Tempo 에 보내기 위한 설정
    endpoint: tempo:4317 # Tempo 컨테이너가 열고 있는 gRPC 포트
    tls: # TLS 인증 없이 보냄을 의미
      insecure: true

service: # 데이터를 어떤 경로로 처리할지
  pipelines:
    metrics: # OTLP(Java) 에서 수신해 prometheus 로 보냄을 의미
      receivers: [otlp]
      exporters: [prometheus]

    traces: # OTPL(Java)에서 보낸 트레이스를 받아 Tempo 로 보냄을 의미
      receivers: [otlp]
      exporters: [otlp/tempo]